import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
	server: {
		NODE_ENV: z
			.enum(["development", "test", "production"])
			.default("development"),
		CLERK_SECRET_KEY: z.string().min(1),
		CLERK_JWT_ISSUER_DOMAIN: z.string().url(),
		CONVEX_DEPLOYMENT: z.string().min(1),
		CONVEX_URL: z.string().url(),
		FAL_KEY: z.string().min(1),
		FIRECRAWL_API_KEY: z.string().optional(),
		FIRECRAWL_API_API_KEY: z.string().optional(),
		FIRECRAWL_PLAN_API_KEY: z.string().optional(),
		IDEALISTA_API_KEY: z.string().optional(),
		IDEALISTA_API_SECRET: z.string().optional(),
		BROWSERBASE_API_KEY: z.string().optional(),
		BROWSERBASE_PROJECT_ID: z.string().optional(),
		STRIPE_SECRET_KEY: z.string().min(1),
		STRIPE_WEBHOOK_SECRET: z.string().optional(),
		WORKFLOW_INGEST_SECRET: z.string().optional(),
		TWILIO_ACCOUNT_SID: z.string().min(1).optional(),
		TWILIO_AUTH_TOKEN: z.string().min(1).optional(),
		TWILIO_WHATSAPP_FROM: z.string().min(1).optional(),
		TWILIO_MESSAGING_SERVICE_SID: z.string().min(1).optional(),
		TWILIO_WEBHOOK_BASE_URL: z.string().url().optional(),
		POSTHOG_API_KEY: z.string().optional(),
		POSTHOG_HOST: z.string().optional(),
	},
	client: {
		NEXT_PUBLIC_APP_URL: z.string().url(),
		NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
		NEXT_PUBLIC_CONVEX_URL: z.string().url(),
		NEXT_PUBLIC_CONVEX_SITE_URL: z.string().url(),
		NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
		NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
		NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().optional(),
	},
	runtimeEnv: {
		NODE_ENV: process.env.NODE_ENV,
		CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
		CLERK_JWT_ISSUER_DOMAIN: process.env.CLERK_JWT_ISSUER_DOMAIN,
		NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
			process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
		NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
		CONVEX_DEPLOYMENT: process.env.CONVEX_DEPLOYMENT,
		CONVEX_URL: process.env.CONVEX_URL,
		FAL_KEY: process.env.FAL_KEY,
		FIRECRAWL_API_KEY: process.env.FIRECRAWL_API_KEY,
		FIRECRAWL_API_API_KEY: process.env.FIRECRAWL_API_API_KEY,
		FIRECRAWL_PLAN_API_KEY: process.env.FIRECRAWL_PLAN_API_KEY,
		IDEALISTA_API_KEY: process.env.IDEALISTA_API_KEY,
		IDEALISTA_API_SECRET: process.env.IDEALISTA_API_SECRET,
		BROWSERBASE_API_KEY: process.env.BROWSERBASE_API_KEY,
		BROWSERBASE_PROJECT_ID: process.env.BROWSERBASE_PROJECT_ID,
		STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
		STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
		WORKFLOW_INGEST_SECRET: process.env.WORKFLOW_INGEST_SECRET,
		TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
		TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
		TWILIO_WHATSAPP_FROM: process.env.TWILIO_WHATSAPP_FROM,
		TWILIO_MESSAGING_SERVICE_SID: process.env.TWILIO_MESSAGING_SERVICE_SID,
		TWILIO_WEBHOOK_BASE_URL: process.env.TWILIO_WEBHOOK_BASE_URL,
		POSTHOG_API_KEY: process.env.POSTHOG_API_KEY,
		POSTHOG_HOST: process.env.POSTHOG_HOST,
		NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
		NEXT_PUBLIC_CONVEX_SITE_URL: process.env.NEXT_PUBLIC_CONVEX_SITE_URL,
		NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
		NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
		NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
			process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
	},
	emptyStringAsUndefined: true,
});
